[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:valkey]
# 關鍵：加上 --daemonize no 讓 Valkey 在前台執行
command=valkey-server --daemonize no --port 6379
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:unbound]
command=/usr/sbin/unbound -c /etc/unbound/unbound.conf
startsecs=0
#startretries=0

[program:clamd]
command=/usr/sbin/clamd -c /etc/clamd.d/scan.conf
startsecs=0
#startretries=0

[program:rspamd]
command=/usr/bin/rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf  -f
startsecs=0

[program:dovecot]
command=/usr/bin/bash /start_dovecot.sh
startsecs=0
#startretries=0

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
startsecs=0
#startretries=0

[program:opendkim]
command=/usr/sbin/opendkim -x /etc/opendkim/opendkim.conf -P /var/run/opendkim/opendkim.pid 
startsecs=0
#startretries=0

[program:crond]
command=/usr/sbin/crond -n &
startsecs=0
#startretries=0

[program:postfix]
command=/usr/sbin/postfix -c /etc/postfix start
startsecs=0
#startretries=0

[program:delayed_queue_daemon]
command=/usr/bin/python3 /usr/lib/dovecot/sieve-pipe/delayed_queue_daemon.py
autostart=true
autorestart=true
startsecs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0



