# /etc/rspamd/kafeiou.d/kafeiou_regexp.conf
# =========================================================================
# 【說明】：本檔案定義專案客製化的正則表達式（Regexp）過濾規則。
# 【載入方式】：由 /etc/rspamd/local.d/regexp.conf 透過以下指令引入生效：
#   .include(try=true,priority=1,duplicate=merge) "$CONFDIR/kafeiou.d/kafeiou_regexp.conf"
# =========================================================================

"RE_EMAIL_ICHEERS" = {
        re = '/@icheers.tw/i{body}';
        score = 20.0;
}
"RE_EMAIL_COLLIERS" = {
        re = '/@colliers.com/i{body}';
        score = 20.0;
}
