# local.d/milter_headers.conf:

# Options

# Add "extended Rspamd headers" (default false) (enables x-spamd-result, x-rspamd-server, x-rspamd-queue-id & x-rspamd-action routines)
extended_spam_headers = true;

# List of routines to enable for authenticated users (default empty); see also `skip_authenticated`
# authenticated_headers = ["authentication-results"];

# Set false to enable all used routines for authenticated users (default true)
# skip_authenticated = true;

# List of routines to enable for local IPs (default empty); see also `skip_local`
# local_headers = ["x-spamd-bar"];

# Set false to enable all used routines for local IPs (default true)
# skip_local = true;

# Routines to use- this is the only required setting (may be omitted if using extended_spam_headers)
use = ["x-spamd-result", "x-rspamd-action", "x-spam-status", "x-spam-flag"];
remove_upstream_spam_flag = false;
headers_modify_mode = "compat";
routines {
  x-spamd-bar {
    header = "X-Spamd-Bar";
    positive = "+";
    negative = "-";
    neutral = "/";
    remove = 0;
  }
}
routines {
  x-spam-status {
    header = "X-Spam-Status";
    remove = 0;
  }
}

