# =========================================================================
# 【公共規則】：AHBL 反垃圾特徵比對清單
# =========================================================================

ahbl_spamsigns_body {
        type = "content";
        filter = "oneline";
        map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-body.map.zst";
        regexp = true;
        symbol = "AHBL_SPAMSIGNS_BODY";
        score 5.0;
        description = "AHBL: Spam signs in body";
}

ahbl_spamsigns_cs {
        type = "content";
        filter = "oneline";
        map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-contactsocial.map.zst";
        regexp = true;
        symbol = "AHBL_SPAMSIGNS_CS";
        score 2.0;
        description = "AHBL: Contact / social spam signs in body";
}

ahbl_badrep_domains_url {
        type = "url";
        map = "https://downloads.ahbl.org/rspamd/ahbl-badrep-domains.map.zst";
        regexp = false;
        symbol = "AHBL_BADREP_DOMAINS_URL";
        score 2.0;
        description = "AHBL: Bad reputation / spam domains in URLs";
}

ahbl_spamsigns_subject {
        type = "header";
        header = "Subject";
        map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-subject.map.zst";
        regexp = true;
        symbol = "AHBL_SPAMSIGNS_SUBJECT";
        score 2.0;
        description = "AHBL: Spam signs in subject";
}

ahbl_spam_email_from {
	type = "from";
	map = "https://downloads.ahbl.org/rspamd/ahbl-spam-email-addy.map.zst";
	symbol = "AHBL_SPAMEMAIL_FROM";
	score 5.0;
	description = "AHBL: Spam email address in From:";
}

# =========================================================================
# 【專案客製】：引入 kafeiou.d 自訂規則與黑白名單
# =========================================================================
.include(try=true,priority=1,duplicate=merge) "$CONFDIR/kafeiou.d/kafeiou_multimap.conf"
