# =========================================================================
# 【專案客製】：引入 kafeiou.d 正則表達式規則
# =========================================================================
.include(try=true,priority=1,duplicate=merge) "$CONFDIR/kafeiou.d/kafeiou_regexp.conf"
