#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
15-Second Delayed Auto-Reply (Vacation) Worker for Postfix + Dovecot Pigeonhole Sieve.
Detaches immediately via double-fork so Dovecot LMTP delivery is never blocked.
Sleeps for 15 seconds in background, then sends the auto-reply email via sendmail.
"""

import sys
import os
import time
import re
import email
from email.header import decode_header
from email.mime.text import MIMEText
from email.utils import parseaddr, formatdate
import subprocess
import json

DELAY_SECONDS = 15
RATE_LIMIT_HOURS = 24
VMAIL_BASE = "/home/vmail"

def decode_mime_words(s):
    if not s:
        return ""
    decoded_fragments = []
    for frag, enc in decode_header(s):
        if isinstance(frag, bytes):
            enc = enc or "utf-8"
            try:
                decoded_fragments.append(frag.decode(enc, errors="replace"))
            except Exception:
                decoded_fragments.append(frag.decode("utf-8", errors="replace"))
        else:
            decoded_fragments.append(str(frag))
    return "".join(decoded_fragments).strip()

def check_and_update_rate_limit(sieve_dir, sender_email):
    """
    Ensures the same sender is only replied once every 24 hours (:days 1 equivalent).
    """
    db_file = os.path.join(sieve_dir, "vacation_rate_limit.json")
    now_ts = time.time()
    records = {}

    if os.path.exists(db_file):
        try:
            with open(db_file, "r", encoding="utf-8") as f:
                records = json.load(f)
        except Exception:
            records = {}

    # Cleanup expired records older than 24 hours
    cutoff = now_ts - (RATE_LIMIT_HOURS * 3600)
    cleaned = {k: v for k, v in records.items() if v > cutoff}

    sender_key = sender_email.lower().strip()
    if sender_key in cleaned:
        # Already replied in last 24 hours, skip
        return False

    # Record new reply timestamp
    cleaned[sender_key] = now_ts
    try:
        with open(db_file, "w", encoding="utf-8") as f:
            json.dump(cleaned, f)
        os.chown(db_file, 1001, 1001)
    except Exception:
        pass

    return True

def send_autoreply_email(owner_email, sender_email, subject, body, orig_msg_id):
    """
    Sends the auto-reply email via system sendmail with correct headers.
    """
    msg = MIMEText(body, _subtype="plain", _charset="utf-8")
    msg["Subject"] = subject
    msg["From"] = owner_email
    msg["To"] = sender_email
    msg["Date"] = formatdate(localtime=True)
    msg["Auto-Submitted"] = "auto-replied"
    msg["Precedence"] = "bulk"
    if orig_msg_id:
        msg["In-Reply-To"] = orig_msg_id
        msg["References"] = orig_msg_id

    sendmail_paths = ["/usr/sbin/sendmail", "/usr/lib/sendmail"]
    sendmail_bin = None
    for p in sendmail_paths:
        if os.path.exists(p):
            sendmail_bin = p
            break

    if sendmail_bin:
        try:
            cmd = [sendmail_bin, "-t", "-oi", "-f", owner_email]
            proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
            proc.communicate(input=msg.as_bytes())
        except Exception as e:
            sys.stderr.write(f"Error sending delayed auto-reply: {e}\n")

def background_delayed_task(owner_email, sender_email, subject, body, orig_msg_id):
    """
    Runs in a detached background daemon process. Sleeps 15s then sends email.
    """
    try:
        time.sleep(DELAY_SECONDS)
        send_autoreply_email(owner_email, sender_email, subject, body, orig_msg_id)
    except Exception as e:
        sys.stderr.write(f"Delayed task error: {e}\n")

def main():
    raw_email = sys.stdin.buffer.read()
    if not raw_email:
        sys.exit(0)

    try:
        msg = email.message_from_bytes(raw_email)
    except Exception:
        sys.exit(0)

    if len(sys.argv) > 1 and sys.argv[1].strip():
        owner_email = sys.argv[1].lower().strip()
    else:
        delivered_to = msg.get("Delivered-To", "") or msg.get("X-Original-To", "") or msg.get("Envelope-To", "") or msg.get("To", "")
        _, owner_email = parseaddr(decode_mime_words(delivered_to))
        owner_email = owner_email.lower().strip()

    if not owner_email:
        sys.exit(0)

    from_header = decode_mime_words(msg.get("From", ""))
    _, sender_email = parseaddr(from_header)
    sender_email = sender_email.lower().strip()

    if not sender_email or sender_email == owner_email:
        sys.exit(0)

    # Check Sieve storage directory for this user
    sieve_dir = os.path.join(VMAIL_BASE, owner_email, "sieve")
    if not os.path.exists(sieve_dir):
        local_part = owner_email.split("@")[0]
        sieve_dir = os.path.join(VMAIL_BASE, local_part, "sieve")
        if not os.path.exists(sieve_dir):
            sys.exit(0)

    # Read config generated by handle_autoreply.py
    cfg_path = os.path.join(sieve_dir, "autoreply_config.json")
    if not os.path.exists(cfg_path):
        sys.exit(0)

    try:
        with open(cfg_path, "r", encoding="utf-8") as f:
            cfg = json.load(f)
    except Exception:
        sys.exit(0)

    if not cfg.get("enabled", False):
        sys.exit(0)

    # Check 24-hour rate limit
    if not check_and_update_rate_limit(sieve_dir, sender_email):
        sys.exit(0)

    reply_subject = cfg.get("subject", "【自動回覆】休假中 / Out of Office")
    reply_body = cfg.get("body", "您好：我目前休假/公出中，將於銷假後儘速處理您的郵件。")
    orig_msg_id = msg.get("Message-ID", "")

    # Double-Fork to detach immediately and release Dovecot LMTP
    try:
        pid = os.fork()
        if pid > 0:
            # Parent exits immediately with code 0 (Dovecot LMTP finishes instantly)
            sys.exit(0)
    except OSError:
        sys.exit(0)

    # First child process
    os.setsid()
    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)
    except OSError:
        sys.exit(0)

    # Daemon child process
    # Redirect standard file descriptors
    try:
        sys.stdout.flush()
        sys.stderr.flush()
        with open(os.devnull, "r") as devnull_r, open(os.devnull, "a+") as devnull_w:
            os.dup2(devnull_r.fileno(), sys.stdin.fileno())
            os.dup2(devnull_w.fileno(), sys.stdout.fileno())
            os.dup2(devnull_w.fileno(), sys.stderr.fileno())
    except Exception:
        pass

    # Execute 15-second delayed auto-reply in background
    background_delayed_task(owner_email, sender_email, reply_subject, reply_body, orig_msg_id)

if __name__ == "__main__":
    main()
