name: Build and Push to Docker Hub

on:
  push:
    branches: [ "rspamd" ]  # 當推送到 main 分支時觸發

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 取得程式碼
        uses: actions/checkout@v4

      - name: 登入 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 建置並推送映像檔
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: inmethod/docker-postfix-ad:latest
